#title: "Srikrishna Bhat"
#email: "bhat.srikrishna11@gmail.com"
#description: "Computer Scientist | Interested in Brain-Computer Interfaces, Machine Learning and Cognitive Psychology"
#baseurl: ""
#url: "https://Srikrishna.github.io"

author:
  name: "Srikrishna Bhat"
  avatar: "images/profile.jpg"
  bio: "BCI and HCI Scientist interested in exploring technologies that empathise with the human condition and augment/aid humans."
  email: "bhat.srikrishna11@gmail.com"
  google_scholar: "https://scholar.google.com/"
  github: "https://github.com/yourusername"
  twitter: "https://twitter.com/yourhandle"
  linkedin: "https://linkedin.com/in/yourprofile"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# paginate: 10
# paginate_path: "/posts/page:num/"
navigation:
  main: "/_data/navigation.yml"

collections:
  publications:
    output: true
  experiences:
    output: true
  CV:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "students"
    values:
      layout: "student"
